name: Build website
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        julia-version: [1.9]

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/cache@v1

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - uses: py-actions/py-dependency-install@v4

      - uses: julia-actions/julia-buildpkg@v1

      - name: Cache Pluto.jl cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
            .build
          key: cache-pluto-${{ github.event.repository.updated_at }}
          restore-keys: cache-pluto-

      - name: Run build.jl
        run: julia --project=. build.jl

      - name: Publish
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: ".build"
          destination-github-username: "ghnem"
          destination-repository-name: "ghnem.github.io"
          user-email: research@abdulrhmnghanem.tech
          target-directory: modeling-and-control-books-in-julia
          target-branch: main
