name: Build website
on:
  push:
    branches:
      - main
  schedule:
    # once every five days at 00:00 UTC
    - cron: "0 0 */5 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        julia-version: ["1.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: julia-actions/cache@v1

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - uses: py-actions/py-dependency-install@v4

      - uses: julia-actions/julia-buildpkg@v1

      - name: Cache Pluto.jl cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
            .build
          key: cache-pluto
          restore-keys: cache-pluto

      - name: Run build.jl
        run: julia --project=. build.jl

      - name: Normalize hrefs
        run: |
          sed -i 's/SysID\.jl\///g' .build/SysID.jl/index.html
          sed -i 's/PracticalModelingAndSimulation\.jl\///g' .build/PracticalModelingAndSimulation.jl/index.html
          sed -i 's/databook\.jl\///g' .build/databook.jl/index.html

      - name: Publish
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: ".build"
          destination-github-username: "ghnem"
          destination-repository-name: "ghnem.github.io"
          user-email: research@abdulrhmnghanem.tech
          target-directory: modeling-and-control-books-in-julia
          target-branch: main

      - name: Delete old cache
        run: gh cache delete cache-pluto || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update cache
        uses: actions/cache/save@v3
        with:
          path: |
            .cache
            .build
          key: cache-pluto
