name: Build website
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        julia-version: [1.9]

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/cache@v1

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Pluto.jl cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: ${{ runner.os }}-julia
          restore-keys: |
            ${{ runner.os }}-julia

      - name: Install Dependencies
        run: |
          julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run build.jl
        run: julia --project=. build.jl
